---
title: "&#32;"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
  
---

<style>
body {
text-align: justify}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## About the project

Climate change poses serious challenges for agricultural communities all over the world. In this project we use the data provided by the GAEZ project to provide benchmark estimates for the damage done to overall agricultural productivity. This is particularly relevant for low-income regions and communities which will have a hard time adapting to falling productivity through changes in technology or crop type.


The motivation for this webpage is to provide early warning to local policy makers. We highlight regions and communities which will suffer significant productivity losses under current planting patterns. Adaptation is a crucial aspect for mediating the economic, social and political repercussions of climate change.


At the same time we hope that this project can contribute to understanding the devastating impact that climate change will have locally and the unequal distribution of its damages. This should inform both efforts of preventing climate change and political negotiations for compensating the losers from the remaining change.



## About the data

For a full overview of the methodology, check out the [model documentation](downloads.html). 
Essentially for cell i, we have the harvesting area of crop c under water conditions w (either rainfed or irrigated) denoted as $har_{icw}$. The data is taken from [GAEZv4](https://gaez.fao.org/) for the year 2010. 
Moreover GAEZv4 provides data on the agro-climatic potential yield for crop *c* in cell *i* for today (observed) and future time periods (estimated). 
For future time periods the estimation/simulation is subject to the assumed climatic conditions of one of the four Relative Concentration Pathways. Thus agro-climatic potential yield is defined as $\gamma_{icw}$ for todays production and as $\gamma_{icwst}$ for future production where s denotes the RCP and t the time period. 

In order to compare future scenarios with todays production, we multiply the harvesting area of crop c in cell i with the corresponding agro-climatic yield for crop c in cell i

$$ \theta_{icwst} = \gamma_{icwst} \times har_{icw} $$

Note that the agro-climatic yield differs from the actual production, widely discussed under yield gaps. 
Also the construction of $\theta_{icwst}$ shows the two major assumptions of our approach

1. High Input Management Assumption
2. Constant harvesting area, i.e. no crop adaptation


The first assumption is predetermined by the agro-climatic potential yield data. It assumes high input management. As this assumptions holds for today's and future data, it cancels out, allowing a focus on just the changes of climatic conditions and the effect on agricultural productivity. Denoted constant technology in _Economic Terms_ , we assume that the farming technology and agricultural inputs remain the same over time. Highly unrealistic, but this allows the focus on the effect of climatic changes.

The second assumption can be described as _no adaptation of crops_, i.e. farmers don't change their set of crops with changing climatic conditions. 
Theoretically this is a very limiting assumptions, as varying climatic conditions might change in favor to certain crops for specific regions, which make them easier to grow etc.. Yet this again allows to identify regions that _will_ have to adapt the most or benefit the most, as their current composition of harvested crops is unsuitable/suitable. 



In order to compare cells with different produced crops, we then aggregate crops in each cell by their caloric yield $ca_c$. 

$$ \theta_{iwst} = \sum_{c = 1}^{C} \theta_{icwst} \times ca_c $$

## About the maps

The maps (visible here!) show either the absolute change in calories or the growth rate of calories, where calories are expressed in people fed yearly (PFY):
$$\frac{\theta_{iwst}}{365 * c_{min}}$$
where $c_{min}$ is calories needed per person per day. After summing the water supply types, the change measure $\omega$ is defined as:


$$\omega_{ist} = \theta_{ist} - \theta_{i} $$
in the absolute case and 
$$\omega_{ist} = \frac{\theta_{ist} - \theta_{i}}{\theta_i} $$

For this application we set $c_min$ at 2700 calories per person per day. 



## Useful links

Most of the data is taken from the [GAEZv4](https://gaez.fao.org/). Check out their model documentation for detailed information

For the sources of additional data, like caloric conversion of crop types data, consult our model documentation.

*Work in Progress*

